// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AzureSandbox")>]
[<assembly: AssemblyProductAttribute("AzureSandbox")>]
[<assembly: AssemblyDescriptionAttribute("AzureSandbox")>]
[<assembly: AssemblyVersionAttribute("2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AzureSandbox"
    let [<Literal>] AssemblyProduct = "AzureSandbox"
    let [<Literal>] AssemblyDescription = "AzureSandbox"
    let [<Literal>] AssemblyVersion = "2.0"
    let [<Literal>] AssemblyFileVersion = "2.0"
    let [<Literal>] AssemblyConfiguration = "Release"
